markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Visu Mahalingam
url: http://visu.me
description: A fantastic blog that is fantastic.
twitter: visu_m
