markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Visu M
author: Visu Mahalingam
url: http://visu.me
description: notes on Tech
twitter: visu_m
linkedin: mvisu
